version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet restore DevOps6/DevOps6.csproj
      - dotnet publish DevOps6/DevOps6.csproj -c Release -o output

artifacts:
  files:
    - '**/*'
  base-directory: output
