version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0       # Use the .NET version of your project
    commands:
      - echo Installing dependencies...
      - dotnet restore

  build:
    commands:
      - echo Building the project...
      - dotnet build -c Release

  post_build:
    commands:
      - echo Publishing the project...
      - dotnet publish -c Release -o ./publish
      - echo Build and publish completed.

artifacts:
  files:
    - '**/*'
  base-directory: publish   # <-- IMPORTANT: ensures EB gets the correct root structure
